Thesis/Controllers/AuthoritiesController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using Project_Test1.Models;
using Syncfusion.XlsIO;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_Test1.Controllers
{
    public class AuthoritiesController : Controller
    {

        // GET: Authorities
        public ActionResult Index(TitileAll ti)
        {
            //ti.user_id_title = "kittisak";
            ViewData["user_id"] = ti.user_id_title;
            ViewData["name"] = ti.name_title;
            ViewBag.Page = "View";
            ConnectDB db = new ConnectDB(); 
            var _viewCompany = "SELECT company_id, name_en, name_th, website, blacklist FROM Company ;";
            _viewCompany += "SELECT * FROM TeachersandAuthorities WHERE teacher_id = '" + ti.user_id_title + "' ";
            DataSet ds = new DataSet();
            ds = db.select(_viewCompany, "Company");
            ViewData["name"] = ds.Tables["Company1"].Rows[0]["name"].ToString();
            return View(ds);
        }



        public ActionResult No02()
        {
            string ReportURL = Server.MapPath("~/prototypeNo/no02.pdf");
            byte[] FileBytes = System.IO.File.ReadAllBytes(ReportURL);
            return File(FileBytes, "application/pdf");
        }



        public ActionResult EditProfile(TitileAll ti)
        {
            ViewData["user_id"] = ti.user_id_title;
            ViewBag.Page = "Profile";
            ViewData["name"] = ti.name_title;
            ViewData["msgAlert"] = ti.msgAlert;
            ConnectDB db = new ConnectDB();
            var _edit = "SELECT * FROM Account where user_id = '" + ti.user_id_title + "' ;";
            _edit += "SELECT * FROM TeachersandAuthorities WHERE teacher_id = '" + ti.user_id_title + "' ";
            DataSet ds = new DataSet();
            ds = db.select(_edit, "Edit");
            return View(ds);
        }
        [HttpPost]
        public ActionResult EditProfile(Account acc, TeachersandAuthorities ta, TitileAll ti)
        {
            acc.date_time_update = DateTime.Now.ToString();
            var _update = "UPDATE Account SET password = '" + acc.password + "', position = '" + acc.position + "', major = '" + acc.major + "', date_time_in = '"
                + acc.date_time_in + "', date_time_update = '" + acc.date_time_update + "' WHERE user_id = '" + acc.user_id + "' ;";
            _update += "UPDATE TeachersandAuthorities SET name = '" + ta.name + "', email = '" + ta.email + "', phone = '" + ta.phone + "', "
                + "status = '" + ta.status + "' WHERE teacher_id = '" + acc.user_id + "' ";
            ConnectDB update = new ConnectDB();
            ti.msgAlert = update.insert_update_delete(_update);
            return RedirectToAction("EditProfile", ti); ;
        }



        //Manage Company -----------------------------------------------------------------
        public ActionResult AddCompany(TitileAll ti)
        {
            ViewData["user_id"] = ti.user_id_title;
            ViewData["name"] = ti.name_title;
            ViewData["msgAlert"] = ti.msgAlert;
            ViewBag.Page = "Add Company";
            
            ConnectDB db = new ConnectDB();
            DataSet ds = new DataSet();
            List<string> ListItems = new List<string>();
            var _Address = "SELECT DISTINCT province FROM PrototypeAddress where not prototype_id = 0 order by province ;";
            ds = db.select(_Address, "PrototypeAddress");
            int _count = ds.Tables["PrototypeAddress"].Rows.Count;
            for (int i = 0; i < _count; i++)
            {
                ListItems.Add(ds.Tables["PrototypeAddress"].Rows[i]["province"].ToString());
            }
            ViewBag.province = ListItems;

            return View();
        }

        [HttpPost]
        public ActionResult AddCompany(Company comp, TitileAll ti)
        {
            ConnectDB select = new ConnectDB();
            var run_id_checkCom = "SELECT MAX(company_id) FROM Company ;SELECT MAX(address_id) FROM Address ;SELECT MAX(contact_id) FROM Contact ;SELECT MAX(rs_id) FROM ReceiveSemester ;";
            run_id_checkCom += "SELECT name_en, name_th, website FROM Company WHERE name_en = '" + comp.name_en[0] + "' or name_th = '" + comp.name_th[0] + "';";
            DataSet ds = new DataSet();
            ds = select.select(run_id_checkCom, "Company_Address_Contact");
            var _chackCom = ds.Tables[4].Rows.Count;

            if (_chackCom == 1)
            {
                ti.msgAlert = "Already";
                //ModelState.Clear();
                return RedirectToAction("AddCompany", ti);
            }
            else
            {
                var _countCom = ds.Tables[0].Rows[0][0].ToString();
                var _countAdd = ds.Tables[1].Rows[0][0].ToString();
                var _countCon = ds.Tables[2].Rows[0][0].ToString();
                var _countRec = ds.Tables[3].Rows[0][0].ToString();

                comp.company_id = new int[1];
                //comp.name_en = new string[1];
                //comp.name_th = new string[1];
                //comp.blacklist = new string[1];

                if (_countCom == "") comp.company_id[0] = 1;
                else comp.company_id[0] = Int32.Parse(_countCom) + 1;
                if (_countAdd == "") comp.address_id = 1;
                else comp.address_id = Int32.Parse(_countAdd) + 1;
                if (_countCon == "") comp.contact_id = 1;
                else comp.contact_id = Int32.Parse(_countCon) + 1;
                if (_countRec == "") comp.rs_id = 1;
                else comp.rs_id = Int32.Parse(_countRec) + 1;

                comp.start_time = DateTime.Now.ToString();
                comp.update_time = DateTime.Now.ToString();
                comp.student_company_id = comp.company_id[0].ToString();
                var _insert = "INSERT INTO Address VALUES (" + comp.address_id + ", " + comp.prototype_id + ", " + comp.company_id[0] + ", 'สถานประกอบการ', '" + comp.number + "', '"
                    + comp.building + "', '" + comp.floor + "', '" + comp.lane + "', '" + comp.road + "' , '" + comp.pX + "' , '" + comp.pY + "') ;";
                _insert += "INSERT INTO Company VALUES (" + comp.company_id[0] + ", " + comp.address_id + ", '" + comp.name_en[0] + "', '" + comp.name_th[0] + "', 'No', '"
                    + comp.phone + "', '" + comp.fax + "', '" + comp.email + "', '" + comp.website + "', '" + comp.business_type + "', '" + comp.all_employee +
                    "', '" + comp.job_request + "', '" + comp.job_time + "', '" + comp.job_day + "', '" + comp.pay + "', '" + comp.accommodation + "', '"
                    + comp.charge_accommodation + "', '" + comp.bus + "', '" + comp.charge_bus + "', '" + comp.welfare + "', '" + comp.exam + "', '"
                    + comp.start_time + "', '" + comp.update_time + "') ;";
                if (comp.con_number == 2 && comp.name != null)
                {
                    _insert += "INSERT INTO Contact VALUES (" + comp.contact_id + ", '" + comp.student_company_id + "', 1, '" + comp.name_s + "', '" + comp.position_s +
                        "', '" + comp.department_s + "', '-', '-', '-') ;";
                    comp.contact_id += 1;
                    _insert += "INSERT INTO Contact VALUES (" + comp.contact_id + ", '" + comp.student_company_id + "', 2, '" + comp.name + "', '" + comp.position +
                        "', '" + comp.department + "', '"
                        + comp.con_phone + "', '" + comp.con_fax + "', '" + comp.con_email + "') ;";
                }
                else
                {
                    _insert += "INSERT INTO Contact VALUES (" + comp.contact_id + ", '" + comp.student_company_id + "', 1, '" + comp.name_s + "', '" + comp.position_s +
                        "', '" + comp.department_s + "', '-', '-', '-') ;";
                }
                if (comp.semester_id1 == 1 && comp.major != null)
                {
                    for (int i = 0; i < comp.major.Length; i++)
                    {
                        _insert += "INSERT INTO ReceiveSemester VALUES (" + comp.rs_id + ", '" + comp.year + "-1', " + comp.company_id[0] + ", '" + comp.major[i] +
                            "', '" + comp.position_of_student[i] + "', '" + comp.job_description[i] + "', " + comp.require[i] + ") ;";
                        comp.rs_id += 1;
                    }
                }
                if (comp.semester_id2 == 1 && comp.major != null)
                {
                    for (int i = 0; i < comp.major.Length; i++)
                    {
                        _insert += "INSERT INTO ReceiveSemester VALUES (" + comp.rs_id + ", '" + comp.year + "-2', " + comp.company_id[0] + ", '" + comp.major[i] +
                            "', '" + comp.position_of_student[i] + "', '" + comp.job_description[i] + "', " + comp.require[i] + ") ;";
                        comp.rs_id += 1;
                    }
                }
                if (comp.semester_id3 == 1 && comp.major != null)
                {
                    for (int i = 0; i < comp.major.Length; i++)
                    {
                        _insert += "INSERT INTO ReceiveSemester VALUES (" + comp.rs_id + ", '" + comp.year + "-3', " + comp.company_id[0] + ", '" + comp.major[i] +
                            "', '" + comp.position_of_student[i] + "', '" + comp.job_description[i] + "', " + comp.require[i] + ") ;";
                        comp.rs_id += 1;
                    }
                }
                ConnectDB insert = new ConnectDB();
                string status = insert.insert_update_delete(_insert);
                ti.msgAlert = status;
                //ViewBag.SuccessMessage = status;
                //ModelState.Clear();
                return RedirectToAction("AddCompany", ti);
            }
        }

Thesis/Views/Authorities/ConfirmStudent.cshtml
@using System.Data
@model DataSet

@{
    ViewBag.Title = "ยืนยันคำขอการสมัคร";
    Layout = "~/Views/Shared/_LayoutAuthoritiesTemplate.cshtml";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#urlonclick').change(function () {
            var url = $(this).val();
            if (url != null && url != '') {
                window.location.href = url;
            }
        });

        $('.btn-recieve').click(function () {
            var url = $(this).val();
            $.alert({
                theme: 'modern',
                title: 'ต้องการรับนักศึกษาคนนี้ ?',
                content: '',
                type: 'green',
                typeAnimated: true,
                boxWidth: '30%',
                useBootstrap: false,
                buttons: {
                    confirm: {
                        text: 'ยืนยัน',
                        btnClass: 'btn-green',
                        action: function () {
                            window.location.href = url;
                        }
                    },
                    cancel: {
                        text: 'ยกเลิก',
                        action: function () {
                            
                        }
                    },
                },
            }); 
        });

        $('.btn-reject').click(function () {
            var url = $(this).val();
            $.alert({
                theme: 'modern',
                title: 'ต้องการปฏิเสธนักศึกษาคนนี้ ?',
                content: '',
                type: 'red',
                typeAnimated: true,
                boxWidth: '30%',
                useBootstrap: false,
                buttons: {
                    confirm: {
                        text: 'ยืนยัน',
                        btnClass: 'btn-red',
                        action: function () {
                            window.location.href = url;
                        }
                    },
                    cancel: {
                        text: 'ยกเลิก',
                        action: function () {
                            
                        }
                    },
                },
            }); 
        });
    });
</script>

<style>
    tr {
        text-align: center;
    }
</style>

<div class="container-fluid">

    <div class="row">
        <div class="col-8" style="margin:auto;">
            <div class="card">
                <div class="card-body">
                    <!-- title -->
                    <div class="align-items-center">
                        <h4 class="card-title">ยืนยันคำขอการสมัครของ นศ.</h4>
                        <h5 class="card-subtitle">รายชื่อสถานประกอบการจะมีรายชื่ีอที่ นศ. ได้มาสมัครไว้เท่านั้น</h5>
                        <hr />
                    </div>
                    <!-- title -->
                    <div class="form-group col-md-12" style="text-align:center;">
                        <div style="margin:auto;">
                            <label class="col-md-5" style="font-weight:bold; text-align:left;">ชื่อสถานประกอบการ :</label>
                            <div class="col-md-5" style="margin:auto;">
                                <select id="urlonclick" class="selectpicker form-control" name="company_id" title="เลือกสถานประกอบการ" data-live-search="true">
                                    @if (ViewData["company_name"].ToString() == "กรุณาเลือกสถานประกอบการ")
                                    {
                                        <option selected hidden disabled>@ViewData["company_name"].ToString()</option>
                                    }
                                    else
                                    {
                                        <option selected hidden>@ViewData["company_name"].ToString()</option>
                                    }
                                    @for (int i = 0; i < Model.Tables[0].Rows.Count; i++)
                                    {
                                        if (Model.Tables[0].Rows[i]["name_th"].ToString().Length > 10)
                                        {
                                            <option value=@Url.Action("ConfirmStudent", "Authorities", new { company_id = Model.Tables[0].Rows[i]["company_id"], company_name =  Model.Tables[0].Rows[i]["name_th"].ToString(), user_id_title = ViewData["user_id"], name_title = ViewData["name"]})>
                                                @Model.Tables[0].Rows[i]["name_th"].ToString()
                                            </option>
                                        }
                                        else
                                        {
                                            <option value=@Url.Action("ConfirmStudent", "Authorities", new { company_id = Model.Tables[0].Rows[i]["company_id"], company_name = @Model.Tables[0].Rows[i]["name_en"].ToString(), user_id_title = ViewData["user_id"], name_title = ViewData["name"] })>
                                                @Model.Tables[0].Rows[i]["name_en"].ToString()
                                            </option>

                                        }
                                    }
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        <hr class="col-md-8" style="margin:auto;" />
                    </div>

                    <div class="table-responsive col-md-12">
                        <table class="table v-middle">
                            <thead>
                                <tr class="bg-light">
                                    <th class="border-top-0">รหัสนักศึกษา</th>
                                    <th class="border-top-0">ชื่อ - สกุลนักศึกษา</th>
                                    <th class="border-top-0">ภาควิชา</th>
                                    <th class="border-top-0"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewData["company_name"].ToString() != "กรุณาเลือกสถานประกอบการ")
                                {
                                    for (int i = 0; i < Model.Tables[1].Rows.Count; i++)
                                    {
                                        <tr>
                                            <td style="vertical-align:middle">@Model.Tables[1].Rows[i]["student_id"]</td>
                                            <td style="vertical-align:middle">@Model.Tables[1].Rows[i]["name_th"]</td>
                                            <td style="vertical-align:middle">@Model.Tables[1].Rows[i]["major"]</td>
                                            <td>
                                                <button class="btn btn-success btn-recieve" value="@Url.Action("UpdateConfirmStudent","Authorities", new { student_id = Model.Tables[1].Rows[i]["student_id"], company_id = Model.Tables[1].Rows[i]["company_id"], company_name = ViewData["company_name"], confirm_status = "รับแล้ว", user_id_title = ViewData["user_id"], name_title = ViewData["name"] })">รับ</button>
                                                <button class="btn btn-danger btn-reject" value="@Url.Action("UpdateConfirmStudent","Authorities", new { student_id = Model.Tables[1].Rows[i]["student_id"], company_id = Model.Tables[1].Rows[i]["company_id"], company_name = ViewData["company_name"], confirm_status = "ปฏิเสธ", user_id_title = ViewData["user_id"], name_title = ViewData["name"] })">ปฏิเสธ</button>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Thesis/Views/Authorities/Index.cshtml
@using System.Data
@model DataSet

@{
    Layout = "~/Views/Shared/_LayoutAuthoritiesTemplate.cshtml";
    ViewBag.Title = "หน้าแรก";
}

<script type="text/javascript">
    $(document).ready(function () {

        $('#viewCompany').DataTable({
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            "order": [[ 3, "asc" ]]
        });

        $('.btn-DeleteCompany').click(function () {
            var url = $(this).val();
            $.alert({
                theme: 'modern',
                title: 'ต้องการลบสถานประกอบการนี้ ?',
                content: 'เลือกยืนยันถ้าต้องการจะลบสถานประกอบการนี้',
                type: 'red',
                typeAnimated: true,
                boxWidth: '30%',
                useBootstrap: false,
                buttons: {
                    confirm: {
                        text: 'ยืนยัน',
                        btnClass: 'btn-red',
                        action: function () {
                            window.location.href = url;
                        }
                    },
                    cancel: {
                        text: 'ยกเลิก',
                        action: function () {
                            
                        }
                    },
                },
            }); 
        });

    });
</script>

<style>
    tr {
        text-align: center;
    }
</style>

<div class="container-fluid">

    <div class="row">
        <!-- column -->
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <!-- title -->
                    <div class="align-items-center col-md-12 form-group">

                        <h4 class="card-title">ตารางแสดงรายชื่อสถานประกอบการ</h4>
                        <h5 class="card-subtitle">การค้นหาสถานประกอบการสามารถพิมพ์หาได้ที่ช่องค้นหาทางขวา</h5>
                        <hr />

                    </div>
                    <!-- title -->

                    <div class="table-responsive col-md-12">
                        <table id="viewCompany" class="table v-middle">
                            <thead>
                                <tr class="bg-light">
                                    <th class="border-top-0" style="text-align:center;">ชื่อภาษาไทย</th>
                                    <th class="border-top-0" style="text-align:center;">ชื่อภาษาอังกฤษ</th>
                                    <th class="border-top-0" style="text-align:center;">เว็บไซต์</th>
                                    <th class="border-top-0" style="text-align:center;">BlackList</th>
                                    <th class="border-top-0" style="text-align:center;">แก้ไข/ลบ</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (DataRow item in Model.Tables["Company"].Rows)
                                {
                                    <tr>
                                        <td>@item["name_th"]</td>
                                        <td>@item["name_en"]</td>
                                        <td><a href="https://@item["website"]" target="_blank">@item["website"]</a></td>
                                        <td>@item["blacklist"]</td>
                                        <td>
                                            @Html.ActionLink("แก้ไข", "EditCompany", new { company_id = @item["company_id"], user_id_title = ViewData["user_id"], name_title = ViewData["name"] }, new { @class = "btn btn-primary", @style = "margin-right:30px;" })
                                            <button class="btn btn-danger btn-DeleteCompany" value="@Url.Action("DeleteCompany","Authorities", new { company_id = @item["company_id"], user_id_title = ViewData["user_id"], name_title = ViewData["name"] })">ลบ</button>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

Thesis/Views/Authorities/Report.cshtml
@using System.Data;
@model DataSet

@{
    ViewBag.Title = "Report";
    Layout = "~/Views/Shared/_LayoutAuthoritiesTemplate.cshtml";
}

<div class="container-fluid" style="margin-top:30px;">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <!-- Row -->



    <div class="row">
        <div class="col-md-9" style="margin:auto;">
            <div class="card">
                <div class="card-body">
                    <div class="form-group" style="text-align:center; margin:auto;">
                        <div class="col-md-12">

                            <h4 class="card-title">พิมพ์ใบรายชื่อและบริษัทที่ออกฝึก</h4>
                            @using (Html.BeginForm("excelReport", "Authorities", null, FormMethod.Post, new { target = "_blank" }))
                            {
                                <div class="form-group">
                                    <label class="col-sm-12">เลือกเทอมการศึกษา</label>
                                    <div class="col-sm-12">
                                        <select class="form-control form-control-line" name="sem" id="major">
                                            <option selected>กรุณาเลือก</option>
                                            @foreach (DataRow sem in Model.Tables[0].Rows)
                                            {
                                                <option value="@sem[0]">@sem[0]</option>

                                            }
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-12">เลือกภาควิชา</label>
                                    <div class="col-sm-12">
                                        <select class="form-control form-control-line" name="major" id="major">
                                            <option selected>กรุณาเลือก</option>
                                            @foreach (DataRow major in Model.Tables[1].Rows)
                                            {
                                                <option value="@major[0]">@major[0]</option>

                                            }
                                        </select>
                                    </div>
                                </div>

                                <button class="btn btn-success" type="submit" style="margin:auto; width:200px;" name="id" value="@ViewData["user_id"]">พิมพ์</button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

Thesis/Views/Authorities/ViewRequire_s.cshtml
@model Project_Test1.Models.Company

@{
    ViewBag.Title = "แสดงข้อมูลการรับนักศึกษา";
    Layout = "~/Views/Shared/_LayoutAuthoritiesTemplate.cshtml";
}

    <script type="text/javascript">
    $(document).ready(function () {
        $('#urlonclick').change(function() {
            var url = $(this).val();
            if (url != null && url != '') {
                window.location.href = url + $("#year").val();
            }
        });

        var year = $("#getYear").val();

        $('#year').datepicker({
            minViewMode: 'years',
            autoclose: true,
            format: 'yyyy',
            orientation: "bottom auto"
        }).datepicker("setDate", new Date('11/11/'+year));

    });
    </script>

    <style>
        tr {
            text-align: center;
        }
    </style>

    <div class="container-fluid">

        <div class="row">
            <!-- column -->
            <div class="col-8" style="margin:auto;">
                <div class="card">
                    <div class="card-body">
                        <!-- title -->
                        <div class="align-items-center">

                            <h4 class="card-title">ตารางแสดงข้อมูลความต้องการของสถานประกอบการ</h4>
                            <h5 class="card-subtitle">**สถานประกอบการที่ติด blacklist จะไม่สามารถเข้าดูได้</h5>
                            <h5 class="card-subtitle">เลือกปีการศึกษา แล้วเลือกสถานประการตารางจะแสดงรายชื่อภาควิชาแต่ละเทอมและจำนวนที่ต้องการรับ นศ.</h5>
                            <hr />

                        </div>
                        <!-- title -->
                    </div>
                    <div class="form-group col-md-12" style="text-align:center;">
                        <div class="col-md-12">
                            <label class="col-md-2" style="font-weight:bold;">ปีการศึกษา :</label>
                            <div class="input-group col-md-2" style="margin:auto;">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                <input id="year" type="text" class="form-control" name="year" style="text-align:center;">
                            </div>
                        </div>
                    </div>

                    <div class="form-group col-md-12" style="text-align:center;">
                        <div class="align-items-center form-horizontal" style="margin:auto;">
                            <label class="col-md-6" style="font-weight:bold; text-align:left;">ชื่อสถานประกอบการ :</label>
                            <div class="col-md-6" style="margin:auto;">
                                <select id="urlonclick" class="selectpicker form-control" name="company_id" data-size="5" data-width="100%" data-live-search="true" style="margin:auto;" required>
                                    @if (Model.name.ToString() == "Please Select")
                                    {
                                        <option selected hidden disabled>@Model.name.ToString()</option>
                                    }
                                    else
                                    {
                                        <option selected hidden>@Model.name.ToString()</option>
                                    }
                                    @for (int i = 0; i < Model.company_id.Length; i++)
                                    {
                                        <option value=@Url.Action("ViewRequire_s", "Authorities", new { user_id_title = ViewData["user_id"], name_title = ViewData["name"], company = Model.company_id[i], name = Model.name_th[i], year = " "})>@Model.name_th[i].ToString()</option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <hr style="margin-bottom:25px" />
                    </div>
                    <div class="table-responsive col-7" style="margin:auto; margin-bottom:100px;">
                        <table id="viewCompany" class="table v-middle">
                            <thead>
                                <tr class="bg-light">
                                    <!--<th class="border-top-0" style="text-align:center;"></th>-->
                                    <th class="border-top-0" style="text-align:center;">เทอม</th>
                                    <th class="border-top-0" style="text-align:center;">ภาควิชา</th>
                                    <th class="border-top-0" style="text-align:center;">จำนวนที่ต้องการ</th>
                                    <!--<th class="border-top-0" style="text-align:center;"></th>-->
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.major != null)
                                {
                                    for (int i = 0; i < Model.major.Length; i++)
                                    {
                                <tr>
                                    <!--<td></td>-->
                                    <td>@Model.term[i]</td>
                                    <td>@Model.major[i]</td>
                                    <td>@Model.require[i]</td>
                                    <!--<td></td>-->
                                </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="hide">
                        <input type="hidden" id="getYear" value="@Model.rs_id" />
                    </div>
                </div>
            </div>
        </div>

    </div>